sudo: required

services:
  - docker

before_install:
  - docker build -t operable/circuit-driver-testing -f Dockerfile.ci .

# Parallelize these tasks
env:
  - TARGET=vet
  - TARGET=ci-coveralls

# Need the job ID in order to upload the Coveralls data
script:
  - docker run -it --rm --env="TRAVIS_JOB_ID=${TRAVIS_JOB_ID}" operable/circuit-driver-testing make $TARGET

notifications:
  slack:
    secure: AIVGIeqiblwxWszg+BIGlgIsu7WlodEYP4A+MKxQEq0GDgLVDP0MWVD7TNQomuWy4Ho1Tb6wvkF/Aou3mvmsF5KWUR3EcMHD4Q6KEokos+sqi42ABFQZP2GeEG5zOjYylb/udpGhDLIWYV8vlwPwM6N4WQVA0hgTfE+LWPiiCanXIdQ9OaR7QgQ6yOI+6DjxxCcr8yoyrEGitHS/yzHyAjSGCt+Vn1InOp5zVb/VyzymeWoX0i/Asz9e184dXRVLDxt/HdiWdFEVA9yPsbsYGZ7w++eqTLGZG6hYlHyoeea1VrFG1GJCVJVhJtAHMjV9yH83D7TSxmbAFtsi+4+JK2bkR5s5JXxk1JOwWSAayeIqRWatwLXSiH3Zfwpae2OFXAGPdc5tI8vXDYkxrGOzNWXrBQJuKeyYdvZ7vvVXnSrt3Rf5Fql4z3vFs7yP2vFkdBw1V1FJi05+m2rUyqiB25kkR2KZQnD2dw5MqwDqizjw1J5V8j44WbyTMgH1SlinP5SDkjFgctUGwhTXdHNqGzhx0WDiGnuCWdZPHTAgJI1tBaPzpmV4e7xvXyKET/JGGYgqHA3I2q8eDM7QEcX97vVHSzkYv5XxyY6mzbSzzJWdk8N73Vr/M+ZnAngi15Wnnk7hys2xsZbf4Zp0JNlQVoDekevo0H/P33IeAeKa/HQ=
